#!/bin/bash

# Execute end-to-end tests

set -e

PORT=8080
TIMEOUT=30

node_modules/.bin/webdriver-manager update

function available() {
  curl -f "http://localhost:$PORT" > /dev/null 2> /dev/null
}

echo -n 'Waiting for the server'
while ! available; do
  echo -n '.'
  sleep 1
  ((TIMEOUT--)) && [[ $TIMEOUT -eq 0 ]] && exit 1
done
echo ' OK'

node_modules/.bin/protractor e2e/protractor.config.js
